description: "Creating everything Rust is missing"
encoding: utf-8
plugins:
- jekyll-readme-index
- jekyll-remote-theme
- jekyll-seo-tag
readme_index:
  enabled:          true
  remove_originals: true
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: false
title: "Corrosion Labs"
