description: "Creating everything Rust is missing"
encoding: utf-8
plugins:
- jekyll-remote-theme
- jekyll-readme-index
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: false
title: "Corrosion Labs"
